// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"context"
)

type Querier interface {
	InsertVideo(ctx context.Context, arg InsertVideoParams) error
	RandomWod(ctx context.Context) (Videos, error)
}

var _ Querier = (*Queries)(nil)
